name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        working-directory: ./backend
        run: pip install -r requirements.pip

      - name: Run pytest
        run: |
          pytest ./backend/test/assignments/2/test_get_user_by_email.py
          pytest ./backend/test/assignments/3/test_create.py

