# full file path ./workflows/on_push.yml
name: On push - perform pytest Workflow

on: push

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
    - name : Checkout code
      uses : actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel pytest-mock
        pip install -r backend/requirements.pip

    - name : Run tests
      run : pytest -s backend/test
