name: Pytest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker-compose -f ../../docker-compose.yml up -d

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.pip

      - name: Wait for MongoDB to start
        run: docker-compose -f path/to/your/docker-compose.yml exec -T mongo bash -c 'while ! mongo --eval "db.stats()" &>/dev/null; do sleep 1; done'

      - name: Unit Tests
        run: |
          docker-compose -f path/to/your/docker-compose.yml exec backend python -m pytest -m unit
